name: Build FAP

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build
        with:
          sdk-channel: release
          sdk-index-url: https://up.unleashedflip.com/directory.json
          app-dir: .  # se i file .c e .fam sono nella root del repo

      - name: Upload compiled .fap
        uses: actions/upload-artifact@v3
        with:
          name: subghz_histogram
          path: ${{ steps.build.outputs.fap-artifacts }}
